// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"

	"github.com/google/uuid"
)

type Payment struct {
	ID             uuid.UUID
	OrderID        uuid.NullUUID
	Amount         string
	Status         string
	IdempotencyKey string
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}
