// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createPayment = `-- name: CreatePayment :exec
INSERT INTO
    payments (
        id,
        order_id,
        amount,
        status,
        idempotency_key,
        created_at,
        updated_at
    )
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreatePaymentParams struct {
	ID             uuid.UUID
	OrderID        uuid.NullUUID
	Amount         string
	Status         string
	IdempotencyKey string
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) error {
	_, err := q.db.ExecContext(ctx, createPayment,
		arg.ID,
		arg.OrderID,
		arg.Amount,
		arg.Status,
		arg.IdempotencyKey,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT
    id,
    order_id,
    amount,
    status,
    idempotency_key,
    created_at,
    updated_at
FROM payments
WHERE
    id = $1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Amount,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByIdempotencyKey = `-- name: GetPaymentByIdempotencyKey :one
SELECT
    id,
    order_id,
    amount,
    status,
    idempotency_key,
    created_at,
    updated_at
FROM payments
WHERE
    idempotency_key = $1
`

func (q *Queries) GetPaymentByIdempotencyKey(ctx context.Context, idempotencyKey string) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByIdempotencyKey, idempotencyKey)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Amount,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByOrderID = `-- name: GetPaymentByOrderID :one
SELECT
    id,
    order_id,
    amount,
    status,
    idempotency_key,
    created_at,
    updated_at
FROM payments
WHERE
    order_id = $1
`

func (q *Queries) GetPaymentByOrderID(ctx context.Context, orderID uuid.NullUUID) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByOrderID, orderID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Amount,
		&i.Status,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :exec
UPDATE payments SET status = $1, updated_at = $2 WHERE id = $3
`

type UpdatePaymentStatusParams struct {
	Status    string
	UpdatedAt sql.NullTime
	ID        uuid.UUID
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updatePaymentStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}
