// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/NguyenAnhQuan-Dev/NKbook-API/internal/handlers"
	"github.com/NguyenAnhQuan-Dev/NKbook-API/internal/repositories"
	"github.com/NguyenAnhQuan-Dev/NKbook-API/internal/services"
	"gorm.io/gorm"
)

// Injectors from bookHandler.go:

func InitBookHandler(db *gorm.DB) (*handlers.BookHandler, error) {
	iBookRepository := repositories.NewBookRepository(db)
	iBookService := services.NewBookService(iBookRepository)
	iAuthorRepository := repositories.NewAuthorRepository(db)
	iAuthorService := services.NewAuthorService(iAuthorRepository)
	iCategoryRepository := repositories.NewCategoryRepository(db)
	iCategoryService := services.NewCategoryService(iCategoryRepository)
	bookHandler := handlers.NewBookHandler(iBookService, iAuthorService, iCategoryService)
	return bookHandler, nil
}

// Injectors from userHandler.go:

func InitAuthHandler(db *gorm.DB) (*handlers.AuthHandler, error) {
	iUserRepository := repositories.NewUserRepository(db)
	iTokenRepository := repositories.NewTokenRepository(db)
	iAuthService := services.NewAuthService(iUserRepository, iTokenRepository)
	authHandler := handlers.NewAuthHandler(iAuthService)
	return authHandler, nil
}
