// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"

	"github.com/google/uuid"
)

type Author struct {
	ID        uuid.UUID
	Name      string
	Bio       sql.NullString
	CreatedAt sql.NullTime
}

type Book struct {
	ID           uuid.UUID
	Title        string
	Description  sql.NullString
	Price        string
	Stock        int32
	AuthorID     uuid.NullUUID
	CategoryID   uuid.NullUUID
	PublisherID  uuid.NullUUID
	CoverImage   sql.NullString
	IsActive     sql.NullBool
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	SearchVector interface{}
}

type Category struct {
	ID        uuid.UUID
	Name      string
	CreatedAt sql.NullTime
}

type Publisher struct {
	ID        uuid.UUID
	Name      string
	CreatedAt sql.NullTime
}
