// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const adjustStock = `-- name: AdjustStock :one
UPDATE books
SET
    stock = stock + $2,
    updated_at = now()
WHERE
    id = $1
RETURNING
    id, title, description, price, stock, author_id, category_id, publisher_id, cover_image, is_active, created_at, updated_at, search_vector
`

type AdjustStockParams struct {
	ID    uuid.UUID
	Stock int32
}

func (q *Queries) AdjustStock(ctx context.Context, arg AdjustStockParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, adjustStock, arg.ID, arg.Stock)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.AuthorID,
		&i.CategoryID,
		&i.PublisherID,
		&i.CoverImage,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
	)
	return i, err
}

const authorExists = `-- name: AuthorExists :one
SELECT EXISTS ( SELECT 1 FROM authors WHERE id = $1 )
`

func (q *Queries) AuthorExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, authorExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const bookExists = `-- name: BookExists :one
SELECT EXISTS ( SELECT 1 FROM books WHERE id = $1 )
`

func (q *Queries) BookExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, bookExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const categoryExists = `-- name: CategoryExists :one
SELECT EXISTS ( SELECT 1 FROM categories WHERE id = $1 )
`

func (q *Queries) CategoryExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, categoryExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const categoryExistsByName = `-- name: CategoryExistsByName :one
SELECT EXISTS ( SELECT 1 FROM categories WHERE name = $1 )
`

func (q *Queries) CategoryExistsByName(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRowContext(ctx, categoryExistsByName, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const changePrice = `-- name: ChangePrice :one
UPDATE books
SET
    price = $2,
    updated_at = now()
WHERE
    id = $1
RETURNING
    id, title, description, price, stock, author_id, category_id, publisher_id, cover_image, is_active, created_at, updated_at, search_vector
`

type ChangePriceParams struct {
	ID    uuid.UUID
	Price string
}

func (q *Queries) ChangePrice(ctx context.Context, arg ChangePriceParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, changePrice, arg.ID, arg.Price)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.AuthorID,
		&i.CategoryID,
		&i.PublisherID,
		&i.CoverImage,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
	)
	return i, err
}

const checkBookStock = `-- name: CheckBookStock :one
SELECT stock FROM books WHERE id = $1
`

func (q *Queries) CheckBookStock(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, checkBookStock, id)
	var stock int32
	err := row.Scan(&stock)
	return stock, err
}

const createAuthor = `-- name: CreateAuthor :one

INSERT INTO
    authors (id, name, bio)
VALUES ($1, $2, $3)
RETURNING
    id, name, bio, created_at
`

type CreateAuthorParams struct {
	ID   uuid.UUID
	Name string
	Bio  sql.NullString
}

// ============================================================================
// AUTHORS QUERIES
// ============================================================================
func (q *Queries) CreateAuthor(ctx context.Context, arg CreateAuthorParams) (Author, error) {
	row := q.db.QueryRowContext(ctx, createAuthor, arg.ID, arg.Name, arg.Bio)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.CreatedAt,
	)
	return i, err
}

const createBook = `-- name: CreateBook :one

INSERT INTO
    books (
        id,
        title,
        description,
        price,
        stock,
        author_id,
        category_id,
        publisher_id,
        cover_image,
        is_active
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10
    )
RETURNING
    id, title, description, price, stock, author_id, category_id, publisher_id, cover_image, is_active, created_at, updated_at, search_vector
`

type CreateBookParams struct {
	ID          uuid.UUID
	Title       string
	Description sql.NullString
	Price       string
	Stock       int32
	AuthorID    uuid.NullUUID
	CategoryID  uuid.NullUUID
	PublisherID uuid.NullUUID
	CoverImage  sql.NullString
	IsActive    sql.NullBool
}

// ============================================================================
// BOOKS QUERIES
// ============================================================================
func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, createBook,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Price,
		arg.Stock,
		arg.AuthorID,
		arg.CategoryID,
		arg.PublisherID,
		arg.CoverImage,
		arg.IsActive,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.AuthorID,
		&i.CategoryID,
		&i.PublisherID,
		&i.CoverImage,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
	)
	return i, err
}

const createCategory = `-- name: CreateCategory :one

INSERT INTO
    categories (id, name)
VALUES ($1, $2)
RETURNING
    id, name, created_at
`

type CreateCategoryParams struct {
	ID   uuid.UUID
	Name string
}

// ============================================================================
// CATEGORIES QUERIES
// ============================================================================
func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory, arg.ID, arg.Name)
	var i Category
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const createPublisher = `-- name: CreatePublisher :one

INSERT INTO
    publishers (id, name)
VALUES ($1, $2)
RETURNING
    id, name, created_at
`

type CreatePublisherParams struct {
	ID   uuid.UUID
	Name string
}

// ============================================================================
// PUBLISHERS QUERIES
// ============================================================================
func (q *Queries) CreatePublisher(ctx context.Context, arg CreatePublisherParams) (Publisher, error) {
	row := q.db.QueryRowContext(ctx, createPublisher, arg.ID, arg.Name)
	var i Publisher
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteAuthor = `-- name: DeleteAuthor :exec
DELETE FROM authors WHERE id = $1
`

func (q *Queries) DeleteAuthor(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAuthor, id)
	return err
}

const deleteBook = `-- name: DeleteBook :exec
DELETE FROM books WHERE id = $1
`

func (q *Queries) DeleteBook(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBook, id)
	return err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, id)
	return err
}

const deletePublisher = `-- name: DeletePublisher :exec
DELETE FROM publishers WHERE id = $1
`

func (q *Queries) DeletePublisher(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePublisher, id)
	return err
}

const getActiveBooks = `-- name: GetActiveBooks :many
SELECT
    b.id, b.title, b.description, b.price, b.stock, b.author_id, b.category_id, b.publisher_id, b.cover_image, b.is_active, b.created_at, b.updated_at, b.search_vector,
    a.name as author_name,
    c.name as category_name,
    p.name as publisher_name
FROM
    books b
    LEFT JOIN authors a ON b.author_id = a.id
    LEFT JOIN categories c ON b.category_id = c.id
    LEFT JOIN publishers p ON b.publisher_id = p.id
WHERE
    b.is_active = true
ORDER BY b.created_at DESC
LIMIT $1
OFFSET
    $2
`

type GetActiveBooksParams struct {
	Limit  int32
	Offset int32
}

type GetActiveBooksRow struct {
	ID            uuid.UUID
	Title         string
	Description   sql.NullString
	Price         string
	Stock         int32
	AuthorID      uuid.NullUUID
	CategoryID    uuid.NullUUID
	PublisherID   uuid.NullUUID
	CoverImage    sql.NullString
	IsActive      sql.NullBool
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	SearchVector  interface{}
	AuthorName    sql.NullString
	CategoryName  sql.NullString
	PublisherName sql.NullString
}

func (q *Queries) GetActiveBooks(ctx context.Context, arg GetActiveBooksParams) ([]GetActiveBooksRow, error) {
	rows, err := q.db.QueryContext(ctx, getActiveBooks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveBooksRow
	for rows.Next() {
		var i GetActiveBooksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.AuthorID,
			&i.CategoryID,
			&i.PublisherID,
			&i.CoverImage,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
			&i.AuthorName,
			&i.CategoryName,
			&i.PublisherName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveBooksCount = `-- name: GetActiveBooksCount :one
SELECT COUNT(*) FROM books WHERE is_active = true
`

func (q *Queries) GetActiveBooksCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getActiveBooksCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAllCategories = `-- name: GetAllCategories :many
SELECT id, name, created_at FROM categories ORDER BY name ASC
`

func (q *Queries) GetAllCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, getAllCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllPublishers = `-- name: GetAllPublishers :many
SELECT id, name, created_at FROM publishers ORDER BY name ASC
`

func (q *Queries) GetAllPublishers(ctx context.Context) ([]Publisher, error) {
	rows, err := q.db.QueryContext(ctx, getAllPublishers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Publisher
	for rows.Next() {
		var i Publisher
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuthorByID = `-- name: GetAuthorByID :one
SELECT id, name, bio, created_at FROM authors WHERE id = $1
`

func (q *Queries) GetAuthorByID(ctx context.Context, id uuid.UUID) (Author, error) {
	row := q.db.QueryRowContext(ctx, getAuthorByID, id)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.CreatedAt,
	)
	return i, err
}

const getAuthors = `-- name: GetAuthors :many
SELECT id, name, bio, created_at FROM authors ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type GetAuthorsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetAuthors(ctx context.Context, arg GetAuthorsParams) ([]Author, error) {
	rows, err := q.db.QueryContext(ctx, getAuthors, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Author
	for rows.Next() {
		var i Author
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Bio,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuthorsCount = `-- name: GetAuthorsCount :one
SELECT COUNT(*) FROM authors
`

func (q *Queries) GetAuthorsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getAuthorsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getBookByID = `-- name: GetBookByID :one
SELECT
    b.id, b.title, b.description, b.price, b.stock, b.author_id, b.category_id, b.publisher_id, b.cover_image, b.is_active, b.created_at, b.updated_at, b.search_vector,
    a.name as author_name,
    c.name as category_name,
    p.name as publisher_name
FROM
    books b
    LEFT JOIN authors a ON b.author_id = a.id
    LEFT JOIN categories c ON b.category_id = c.id
    LEFT JOIN publishers p ON b.publisher_id = p.id
WHERE
    b.id = $1
`

type GetBookByIDRow struct {
	ID            uuid.UUID
	Title         string
	Description   sql.NullString
	Price         string
	Stock         int32
	AuthorID      uuid.NullUUID
	CategoryID    uuid.NullUUID
	PublisherID   uuid.NullUUID
	CoverImage    sql.NullString
	IsActive      sql.NullBool
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	SearchVector  interface{}
	AuthorName    sql.NullString
	CategoryName  sql.NullString
	PublisherName sql.NullString
}

func (q *Queries) GetBookByID(ctx context.Context, id uuid.UUID) (GetBookByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getBookByID, id)
	var i GetBookByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.AuthorID,
		&i.CategoryID,
		&i.PublisherID,
		&i.CoverImage,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
		&i.AuthorName,
		&i.CategoryName,
		&i.PublisherName,
	)
	return i, err
}

const getBookByIDSimple = `-- name: GetBookByIDSimple :one
SELECT id, title, description, price, stock, author_id, category_id, publisher_id, cover_image, is_active, created_at, updated_at, search_vector FROM books WHERE id = $1
`

func (q *Queries) GetBookByIDSimple(ctx context.Context, id uuid.UUID) (Book, error) {
	row := q.db.QueryRowContext(ctx, getBookByIDSimple, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.AuthorID,
		&i.CategoryID,
		&i.PublisherID,
		&i.CoverImage,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
	)
	return i, err
}

const getBooks = `-- name: GetBooks :many
SELECT
    b.id, b.title, b.description, b.price, b.stock, b.author_id, b.category_id, b.publisher_id, b.cover_image, b.is_active, b.created_at, b.updated_at, b.search_vector,
    a.name as author_name,
    c.name as category_name,
    p.name as publisher_name
FROM
    books b
    LEFT JOIN authors a ON b.author_id = a.id
    LEFT JOIN categories c ON b.category_id = c.id
    LEFT JOIN publishers p ON b.publisher_id = p.id
ORDER BY b.created_at DESC
LIMIT $1
OFFSET
    $2
`

type GetBooksParams struct {
	Limit  int32
	Offset int32
}

type GetBooksRow struct {
	ID            uuid.UUID
	Title         string
	Description   sql.NullString
	Price         string
	Stock         int32
	AuthorID      uuid.NullUUID
	CategoryID    uuid.NullUUID
	PublisherID   uuid.NullUUID
	CoverImage    sql.NullString
	IsActive      sql.NullBool
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	SearchVector  interface{}
	AuthorName    sql.NullString
	CategoryName  sql.NullString
	PublisherName sql.NullString
}

func (q *Queries) GetBooks(ctx context.Context, arg GetBooksParams) ([]GetBooksRow, error) {
	rows, err := q.db.QueryContext(ctx, getBooks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBooksRow
	for rows.Next() {
		var i GetBooksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.AuthorID,
			&i.CategoryID,
			&i.PublisherID,
			&i.CoverImage,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
			&i.AuthorName,
			&i.CategoryName,
			&i.PublisherName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBooksByAuthor = `-- name: GetBooksByAuthor :many
SELECT
    b.id, b.title, b.description, b.price, b.stock, b.author_id, b.category_id, b.publisher_id, b.cover_image, b.is_active, b.created_at, b.updated_at, b.search_vector,
    a.name as author_name,
    c.name as category_name,
    p.name as publisher_name
FROM
    books b
    LEFT JOIN authors a ON b.author_id = a.id
    LEFT JOIN categories c ON b.category_id = c.id
    LEFT JOIN publishers p ON b.publisher_id = p.id
WHERE
    b.author_id = $1
    AND b.is_active = true
ORDER BY b.created_at DESC
LIMIT $2
OFFSET
    $3
`

type GetBooksByAuthorParams struct {
	AuthorID uuid.NullUUID
	Limit    int32
	Offset   int32
}

type GetBooksByAuthorRow struct {
	ID            uuid.UUID
	Title         string
	Description   sql.NullString
	Price         string
	Stock         int32
	AuthorID      uuid.NullUUID
	CategoryID    uuid.NullUUID
	PublisherID   uuid.NullUUID
	CoverImage    sql.NullString
	IsActive      sql.NullBool
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	SearchVector  interface{}
	AuthorName    sql.NullString
	CategoryName  sql.NullString
	PublisherName sql.NullString
}

func (q *Queries) GetBooksByAuthor(ctx context.Context, arg GetBooksByAuthorParams) ([]GetBooksByAuthorRow, error) {
	rows, err := q.db.QueryContext(ctx, getBooksByAuthor, arg.AuthorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBooksByAuthorRow
	for rows.Next() {
		var i GetBooksByAuthorRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.AuthorID,
			&i.CategoryID,
			&i.PublisherID,
			&i.CoverImage,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
			&i.AuthorName,
			&i.CategoryName,
			&i.PublisherName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBooksByCategory = `-- name: GetBooksByCategory :many
SELECT
    b.id, b.title, b.description, b.price, b.stock, b.author_id, b.category_id, b.publisher_id, b.cover_image, b.is_active, b.created_at, b.updated_at, b.search_vector,
    a.name as author_name,
    c.name as category_name,
    p.name as publisher_name
FROM
    books b
    LEFT JOIN authors a ON b.author_id = a.id
    LEFT JOIN categories c ON b.category_id = c.id
    LEFT JOIN publishers p ON b.publisher_id = p.id
WHERE
    b.category_id = $1
    AND b.is_active = true
ORDER BY b.created_at DESC
LIMIT $2
OFFSET
    $3
`

type GetBooksByCategoryParams struct {
	CategoryID uuid.NullUUID
	Limit      int32
	Offset     int32
}

type GetBooksByCategoryRow struct {
	ID            uuid.UUID
	Title         string
	Description   sql.NullString
	Price         string
	Stock         int32
	AuthorID      uuid.NullUUID
	CategoryID    uuid.NullUUID
	PublisherID   uuid.NullUUID
	CoverImage    sql.NullString
	IsActive      sql.NullBool
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	SearchVector  interface{}
	AuthorName    sql.NullString
	CategoryName  sql.NullString
	PublisherName sql.NullString
}

func (q *Queries) GetBooksByCategory(ctx context.Context, arg GetBooksByCategoryParams) ([]GetBooksByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getBooksByCategory, arg.CategoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBooksByCategoryRow
	for rows.Next() {
		var i GetBooksByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.AuthorID,
			&i.CategoryID,
			&i.PublisherID,
			&i.CoverImage,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
			&i.AuthorName,
			&i.CategoryName,
			&i.PublisherName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBooksByPriceRange = `-- name: GetBooksByPriceRange :many
SELECT
    b.id, b.title, b.description, b.price, b.stock, b.author_id, b.category_id, b.publisher_id, b.cover_image, b.is_active, b.created_at, b.updated_at, b.search_vector,
    a.name as author_name,
    c.name as category_name,
    p.name as publisher_name
FROM
    books b
    LEFT JOIN authors a ON b.author_id = a.id
    LEFT JOIN categories c ON b.category_id = c.id
    LEFT JOIN publishers p ON b.publisher_id = p.id
WHERE
    b.price BETWEEN $1 AND $2
    AND b.is_active = true
ORDER BY b.price ASC
LIMIT $3
OFFSET
    $4
`

type GetBooksByPriceRangeParams struct {
	Price   string
	Price_2 string
	Limit   int32
	Offset  int32
}

type GetBooksByPriceRangeRow struct {
	ID            uuid.UUID
	Title         string
	Description   sql.NullString
	Price         string
	Stock         int32
	AuthorID      uuid.NullUUID
	CategoryID    uuid.NullUUID
	PublisherID   uuid.NullUUID
	CoverImage    sql.NullString
	IsActive      sql.NullBool
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	SearchVector  interface{}
	AuthorName    sql.NullString
	CategoryName  sql.NullString
	PublisherName sql.NullString
}

func (q *Queries) GetBooksByPriceRange(ctx context.Context, arg GetBooksByPriceRangeParams) ([]GetBooksByPriceRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, getBooksByPriceRange,
		arg.Price,
		arg.Price_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBooksByPriceRangeRow
	for rows.Next() {
		var i GetBooksByPriceRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.AuthorID,
			&i.CategoryID,
			&i.PublisherID,
			&i.CoverImage,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
			&i.AuthorName,
			&i.CategoryName,
			&i.PublisherName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBooksByPublisher = `-- name: GetBooksByPublisher :many
SELECT
    b.id, b.title, b.description, b.price, b.stock, b.author_id, b.category_id, b.publisher_id, b.cover_image, b.is_active, b.created_at, b.updated_at, b.search_vector,
    a.name as author_name,
    c.name as category_name,
    p.name as publisher_name
FROM
    books b
    LEFT JOIN authors a ON b.author_id = a.id
    LEFT JOIN categories c ON b.category_id = c.id
    LEFT JOIN publishers p ON b.publisher_id = p.id
WHERE
    b.publisher_id = $1
    AND b.is_active = true
ORDER BY b.created_at DESC
LIMIT $2
OFFSET
    $3
`

type GetBooksByPublisherParams struct {
	PublisherID uuid.NullUUID
	Limit       int32
	Offset      int32
}

type GetBooksByPublisherRow struct {
	ID            uuid.UUID
	Title         string
	Description   sql.NullString
	Price         string
	Stock         int32
	AuthorID      uuid.NullUUID
	CategoryID    uuid.NullUUID
	PublisherID   uuid.NullUUID
	CoverImage    sql.NullString
	IsActive      sql.NullBool
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	SearchVector  interface{}
	AuthorName    sql.NullString
	CategoryName  sql.NullString
	PublisherName sql.NullString
}

func (q *Queries) GetBooksByPublisher(ctx context.Context, arg GetBooksByPublisherParams) ([]GetBooksByPublisherRow, error) {
	rows, err := q.db.QueryContext(ctx, getBooksByPublisher, arg.PublisherID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBooksByPublisherRow
	for rows.Next() {
		var i GetBooksByPublisherRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.AuthorID,
			&i.CategoryID,
			&i.PublisherID,
			&i.CoverImage,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
			&i.AuthorName,
			&i.CategoryName,
			&i.PublisherName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBooksCount = `-- name: GetBooksCount :one
SELECT COUNT(*) FROM books
`

func (q *Queries) GetBooksCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getBooksCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCategories = `-- name: GetCategories :many
SELECT id, name, created_at FROM categories ORDER BY name ASC LIMIT $1 OFFSET $2
`

type GetCategoriesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetCategories(ctx context.Context, arg GetCategoriesParams) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, getCategories, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoriesCount = `-- name: GetCategoriesCount :one
SELECT COUNT(*) FROM categories
`

func (q *Queries) GetCategoriesCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCategoriesCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, name, created_at FROM categories WHERE id = $1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id uuid.UUID) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getLowStockBooks = `-- name: GetLowStockBooks :many
SELECT
    b.id, b.title, b.description, b.price, b.stock, b.author_id, b.category_id, b.publisher_id, b.cover_image, b.is_active, b.created_at, b.updated_at, b.search_vector,
    a.name as author_name,
    c.name as category_name,
    p.name as publisher_name
FROM
    books b
    LEFT JOIN authors a ON b.author_id = a.id
    LEFT JOIN categories c ON b.category_id = c.id
    LEFT JOIN publishers p ON b.publisher_id = p.id
WHERE
    b.stock <= $1
ORDER BY b.stock ASC
LIMIT $2
OFFSET
    $3
`

type GetLowStockBooksParams struct {
	Stock  int32
	Limit  int32
	Offset int32
}

type GetLowStockBooksRow struct {
	ID            uuid.UUID
	Title         string
	Description   sql.NullString
	Price         string
	Stock         int32
	AuthorID      uuid.NullUUID
	CategoryID    uuid.NullUUID
	PublisherID   uuid.NullUUID
	CoverImage    sql.NullString
	IsActive      sql.NullBool
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	SearchVector  interface{}
	AuthorName    sql.NullString
	CategoryName  sql.NullString
	PublisherName sql.NullString
}

func (q *Queries) GetLowStockBooks(ctx context.Context, arg GetLowStockBooksParams) ([]GetLowStockBooksRow, error) {
	rows, err := q.db.QueryContext(ctx, getLowStockBooks, arg.Stock, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLowStockBooksRow
	for rows.Next() {
		var i GetLowStockBooksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.AuthorID,
			&i.CategoryID,
			&i.PublisherID,
			&i.CoverImage,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
			&i.AuthorName,
			&i.CategoryName,
			&i.PublisherName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublisherByID = `-- name: GetPublisherByID :one
SELECT id, name, created_at FROM publishers WHERE id = $1
`

func (q *Queries) GetPublisherByID(ctx context.Context, id uuid.UUID) (Publisher, error) {
	row := q.db.QueryRowContext(ctx, getPublisherByID, id)
	var i Publisher
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getPublishers = `-- name: GetPublishers :many
SELECT id, name, created_at FROM publishers ORDER BY name ASC LIMIT $1 OFFSET $2
`

type GetPublishersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetPublishers(ctx context.Context, arg GetPublishersParams) ([]Publisher, error) {
	rows, err := q.db.QueryContext(ctx, getPublishers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Publisher
	for rows.Next() {
		var i Publisher
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublishersCount = `-- name: GetPublishersCount :one
SELECT COUNT(*) FROM publishers
`

func (q *Queries) GetPublishersCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getPublishersCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const publisherExists = `-- name: PublisherExists :one
SELECT EXISTS ( SELECT 1 FROM publishers WHERE id = $1 )
`

func (q *Queries) PublisherExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, publisherExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const searchBooks = `-- name: SearchBooks :many
SELECT
    b.id, b.title, b.description, b.price, b.stock, b.author_id, b.category_id, b.publisher_id, b.cover_image, b.is_active, b.created_at, b.updated_at, b.search_vector,
    a.name as author_name,
    c.name as category_name,
    p.name as publisher_name,
    ts_rank(
        b.search_vector,
        plainto_tsquery('simple', $1)
    ) as rank
FROM
    books b
    LEFT JOIN authors a ON b.author_id = a.id
    LEFT JOIN categories c ON b.category_id = c.id
    LEFT JOIN publishers p ON b.publisher_id = p.id
WHERE
    b.search_vector @@ plainto_tsquery('simple', $1)
    AND b.is_active = true
ORDER BY rank DESC, b.created_at DESC
LIMIT $2
OFFSET
    $3
`

type SearchBooksParams struct {
	PlaintoTsquery string
	Limit          int32
	Offset         int32
}

type SearchBooksRow struct {
	ID            uuid.UUID
	Title         string
	Description   sql.NullString
	Price         string
	Stock         int32
	AuthorID      uuid.NullUUID
	CategoryID    uuid.NullUUID
	PublisherID   uuid.NullUUID
	CoverImage    sql.NullString
	IsActive      sql.NullBool
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	SearchVector  interface{}
	AuthorName    sql.NullString
	CategoryName  sql.NullString
	PublisherName sql.NullString
	Rank          float32
}

func (q *Queries) SearchBooks(ctx context.Context, arg SearchBooksParams) ([]SearchBooksRow, error) {
	rows, err := q.db.QueryContext(ctx, searchBooks, arg.PlaintoTsquery, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchBooksRow
	for rows.Next() {
		var i SearchBooksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.AuthorID,
			&i.CategoryID,
			&i.PublisherID,
			&i.CoverImage,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SearchVector,
			&i.AuthorName,
			&i.CategoryName,
			&i.PublisherName,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchBooksCount = `-- name: SearchBooksCount :one
SELECT COUNT(*)
FROM books b
WHERE
    b.search_vector @@ plainto_tsquery('simple', $1)
    AND b.is_active = true
`

func (q *Queries) SearchBooksCount(ctx context.Context, plaintoTsquery string) (int64, error) {
	row := q.db.QueryRowContext(ctx, searchBooksCount, plaintoTsquery)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const setBookActive = `-- name: SetBookActive :one
UPDATE books
SET
    is_active = $2,
    updated_at = now()
WHERE
    id = $1
RETURNING
    id, title, description, price, stock, author_id, category_id, publisher_id, cover_image, is_active, created_at, updated_at, search_vector
`

type SetBookActiveParams struct {
	ID       uuid.UUID
	IsActive sql.NullBool
}

func (q *Queries) SetBookActive(ctx context.Context, arg SetBookActiveParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, setBookActive, arg.ID, arg.IsActive)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.AuthorID,
		&i.CategoryID,
		&i.PublisherID,
		&i.CoverImage,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
	)
	return i, err
}

const toggleBookActive = `-- name: ToggleBookActive :one
UPDATE books
SET
    is_active = NOT is_active,
    updated_at = now()
WHERE
    id = $1
RETURNING
    id, title, description, price, stock, author_id, category_id, publisher_id, cover_image, is_active, created_at, updated_at, search_vector
`

func (q *Queries) ToggleBookActive(ctx context.Context, id uuid.UUID) (Book, error) {
	row := q.db.QueryRowContext(ctx, toggleBookActive, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.AuthorID,
		&i.CategoryID,
		&i.PublisherID,
		&i.CoverImage,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
	)
	return i, err
}

const updateAuthor = `-- name: UpdateAuthor :one
UPDATE authors
SET
    name = COALESCE($1, name),
    bio = COALESCE($2, bio)
WHERE
    id = $3
RETURNING
    id, name, bio, created_at
`

type UpdateAuthorParams struct {
	Name sql.NullString
	Bio  sql.NullString
	ID   uuid.UUID
}

func (q *Queries) UpdateAuthor(ctx context.Context, arg UpdateAuthorParams) (Author, error) {
	row := q.db.QueryRowContext(ctx, updateAuthor, arg.Name, arg.Bio, arg.ID)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.CreatedAt,
	)
	return i, err
}

const updateBook = `-- name: UpdateBook :one
UPDATE books
SET
    title = COALESCE($1, title),
    description = COALESCE(
        $2,
        description
    ),
    price = COALESCE($3, price),
    stock = COALESCE($4, stock),
    author_id = COALESCE(
        $5,
        author_id
    ),
    category_id = COALESCE(
        $6,
        category_id
    ),
    publisher_id = COALESCE(
        $7,
        publisher_id
    ),
    cover_image = COALESCE(
        $8,
        cover_image
    ),
    updated_at = now()
WHERE
    id = $9
RETURNING
    id, title, description, price, stock, author_id, category_id, publisher_id, cover_image, is_active, created_at, updated_at, search_vector
`

type UpdateBookParams struct {
	Title       sql.NullString
	Description sql.NullString
	Price       sql.NullString
	Stock       sql.NullInt32
	AuthorID    uuid.NullUUID
	CategoryID  uuid.NullUUID
	PublisherID uuid.NullUUID
	CoverImage  sql.NullString
	ID          uuid.UUID
}

func (q *Queries) UpdateBook(ctx context.Context, arg UpdateBookParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, updateBook,
		arg.Title,
		arg.Description,
		arg.Price,
		arg.Stock,
		arg.AuthorID,
		arg.CategoryID,
		arg.PublisherID,
		arg.CoverImage,
		arg.ID,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.AuthorID,
		&i.CategoryID,
		&i.PublisherID,
		&i.CoverImage,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SearchVector,
	)
	return i, err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories SET name = $2 WHERE id = $1 RETURNING id, name, created_at
`

type UpdateCategoryParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, updateCategory, arg.ID, arg.Name)
	var i Category
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const updatePublisher = `-- name: UpdatePublisher :one
UPDATE publishers SET name = $2 WHERE id = $1 RETURNING id, name, created_at
`

type UpdatePublisherParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) UpdatePublisher(ctx context.Context, arg UpdatePublisherParams) (Publisher, error) {
	row := q.db.QueryRowContext(ctx, updatePublisher, arg.ID, arg.Name)
	var i Publisher
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
