services:
  mysql:
    image: mysql:8.0
    container_name: nhbook-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "nhbook"
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "nhbookroot"
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
