// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type User struct {
	ID           string
	Username     string
	Email        string
	PasswordHash string
	DisplayName  sql.NullString
	Phone        sql.NullString
	IsAdmin      sql.NullBool
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}
