// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :execresult
INSERT INTO
    users (
        ` + "`" + `id` + "`" + `,
        username,
        email,
        password_hash,
        phone
    )
VALUES (?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	ID           string
	Username     string
	Email        string
	PasswordHash string
	Phone        sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Phone,
	)
}

const deleteUserByID = `-- name: DeleteUserByID :exec
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUserByID(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUserByID, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    id,
    username,
    display_name,
    email,
    password_hash,
    phone,
    is_admin,
    created_at,
    updated_at
FROM users
WHERE
    email = ?
LIMIT 1
`

type GetUserByEmailRow struct {
	ID           string
	Username     string
	DisplayName  sql.NullString
	Email        string
	PasswordHash string
	Phone        sql.NullString
	IsAdmin      sql.NullBool
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.PasswordHash,
		&i.Phone,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    id,
    username,
    email,
    display_name,
    password_hash,
    phone,
    is_admin,
    created_at,
    updated_at
FROM users
WHERE
    id = ?
LIMIT 1
`

type GetUserByIDRow struct {
	ID           string
	Username     string
	Email        string
	DisplayName  sql.NullString
	PasswordHash string
	Phone        sql.NullString
	IsAdmin      sql.NullBool
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Phone,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT
    id,
    username,
    display_name,
    email,
    phone,
    is_admin,
    created_at,
    updated_at
FROM users
ORDER BY created_at DESC
`

type ListUsersRow struct {
	ID          string
	Username    string
	DisplayName sql.NullString
	Email       string
	Phone       sql.NullString
	IsAdmin     sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.Email,
			&i.Phone,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET
    display_name = COALESCE(?, full_name),
    email = COALESCE(?, email),
    phone = COALESCE(?, phone_number),
    is_admin = COALESCE(?, is_admin),
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = ?
`

type UpdateUserParams struct {
	DisplayName sql.NullString
	Email       string
	Phone       sql.NullString
	IsAdmin     sql.NullBool
	ID          string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.DisplayName,
		arg.Email,
		arg.Phone,
		arg.IsAdmin,
		arg.ID,
	)
	return err
}
