// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"

	"github.com/google/uuid"
)

type Order struct {
	ID          uuid.UUID
	UserID      uuid.NullUUID
	TotalAmount string
	Status      string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type OrderItem struct {
	ID                uuid.UUID
	OrderID           uuid.NullUUID
	BookID            uuid.NullUUID
	BookTitleSnapshot sql.NullString
	PriceSnapshot     sql.NullString
	Quantity          int32
	CreatedAt         sql.NullTime
}
