// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createOrder = `-- name: CreateOrder :exec
INSERT INTO
    orders (
        id,
        user_id,
        total_amount,
        status,
        created_at,
        updated_at
    )
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateOrderParams struct {
	ID          uuid.UUID
	UserID      uuid.NullUUID
	TotalAmount string
	Status      string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) error {
	_, err := q.db.ExecContext(ctx, createOrder,
		arg.ID,
		arg.UserID,
		arg.TotalAmount,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createOrderItem = `-- name: CreateOrderItem :exec
INSERT INTO
    order_items (
        id,
        order_id,
        book_id,
        book_title_snapshot,
        price_snapshot,
        quantity,
        created_at
    )
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateOrderItemParams struct {
	ID                uuid.UUID
	OrderID           uuid.NullUUID
	BookID            uuid.NullUUID
	BookTitleSnapshot sql.NullString
	PriceSnapshot     sql.NullString
	Quantity          int32
	CreatedAt         sql.NullTime
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error {
	_, err := q.db.ExecContext(ctx, createOrderItem,
		arg.ID,
		arg.OrderID,
		arg.BookID,
		arg.BookTitleSnapshot,
		arg.PriceSnapshot,
		arg.Quantity,
		arg.CreatedAt,
	)
	return err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT
    id,
    user_id,
    total_amount,
    status,
    created_at,
    updated_at
FROM orders
WHERE
    id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TotalAmount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderItems = `-- name: GetOrderItems :many
SELECT
    id,
    order_id,
    book_id,
    book_title_snapshot,
    price_snapshot,
    quantity,
    created_at
FROM order_items
WHERE
    order_id = $1
`

func (q *Queries) GetOrderItems(ctx context.Context, orderID uuid.NullUUID) ([]OrderItem, error) {
	rows, err := q.db.QueryContext(ctx, getOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.BookID,
			&i.BookTitleSnapshot,
			&i.PriceSnapshot,
			&i.Quantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrdersByUserID = `-- name: GetOrdersByUserID :many
SELECT
    id,
    user_id,
    total_amount,
    status,
    created_at,
    updated_at
FROM orders
WHERE
    user_id = $1
ORDER BY created_at DESC
LIMIT $2
OFFSET
    $3
`

type GetOrdersByUserIDParams struct {
	UserID uuid.NullUUID
	Limit  int32
	Offset int32
}

func (q *Queries) GetOrdersByUserID(ctx context.Context, arg GetOrdersByUserIDParams) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, getOrdersByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TotalAmount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrdersCountByUserID = `-- name: GetOrdersCountByUserID :one
SELECT COUNT(*) as total FROM orders WHERE user_id = $1
`

func (q *Queries) GetOrdersCountByUserID(ctx context.Context, userID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getOrdersCountByUserID, userID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders SET status = $1, updated_at = $2 WHERE id = $3
`

type UpdateOrderStatusParams struct {
	Status    string
	UpdatedAt sql.NullTime
	ID        uuid.UUID
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}
