// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"

	"github.com/google/uuid"
)

type Cart struct {
	ID        uuid.UUID
	UserID    uuid.NullUUID
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type CartItem struct {
	ID        uuid.UUID
	CartID    uuid.NullUUID
	BookID    uuid.NullUUID
	Quantity  int32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
