// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addCartItem = `-- name: AddCartItem :exec
INSERT INTO
    cart_items (
        id,
        cart_id,
        book_id,
        quantity,
        created_at,
        updated_at
    )
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (cart_id, book_id) DO
UPDATE
SET
    quantity = cart_items.quantity + EXCLUDED.quantity,
    updated_at = EXCLUDED.updated_at
`

type AddCartItemParams struct {
	ID        uuid.UUID
	CartID    uuid.NullUUID
	BookID    uuid.NullUUID
	Quantity  int32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) AddCartItem(ctx context.Context, arg AddCartItemParams) error {
	_, err := q.db.ExecContext(ctx, addCartItem,
		arg.ID,
		arg.CartID,
		arg.BookID,
		arg.Quantity,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const clearCartItems = `-- name: ClearCartItems :exec
DELETE FROM cart_items WHERE cart_id = $1
`

func (q *Queries) ClearCartItems(ctx context.Context, cartID uuid.NullUUID) error {
	_, err := q.db.ExecContext(ctx, clearCartItems, cartID)
	return err
}

const createCart = `-- name: CreateCart :exec
INSERT INTO
    carts (
        id,
        user_id,
        created_at,
        updated_at
    )
VALUES ($1, $2, $3, $4)
`

type CreateCartParams struct {
	ID        uuid.UUID
	UserID    uuid.NullUUID
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) CreateCart(ctx context.Context, arg CreateCartParams) error {
	_, err := q.db.ExecContext(ctx, createCart,
		arg.ID,
		arg.UserID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteCart = `-- name: DeleteCart :exec
DELETE FROM carts WHERE id = $1
`

func (q *Queries) DeleteCart(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCart, id)
	return err
}

const getCartByUserID = `-- name: GetCartByUserID :one
SELECT
    id,
    user_id,
    created_at,
    updated_at
FROM carts
WHERE
    user_id = $1
`

func (q *Queries) GetCartByUserID(ctx context.Context, userID uuid.NullUUID) (Cart, error) {
	row := q.db.QueryRowContext(ctx, getCartByUserID, userID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCartItemByBookID = `-- name: GetCartItemByBookID :one
SELECT
    id,
    cart_id,
    book_id,
    quantity,
    created_at,
    updated_at
FROM cart_items
WHERE
    cart_id = $1
    AND book_id = $2
`

type GetCartItemByBookIDParams struct {
	CartID uuid.NullUUID
	BookID uuid.NullUUID
}

func (q *Queries) GetCartItemByBookID(ctx context.Context, arg GetCartItemByBookIDParams) (CartItem, error) {
	row := q.db.QueryRowContext(ctx, getCartItemByBookID, arg.CartID, arg.BookID)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.BookID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCartItems = `-- name: GetCartItems :many
SELECT
    id,
    cart_id,
    book_id,
    quantity,
    created_at,
    updated_at
FROM cart_items
WHERE
    cart_id = $1
`

func (q *Queries) GetCartItems(ctx context.Context, cartID uuid.NullUUID) ([]CartItem, error) {
	rows, err := q.db.QueryContext(ctx, getCartItems, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CartItem
	for rows.Next() {
		var i CartItem
		if err := rows.Scan(
			&i.ID,
			&i.CartID,
			&i.BookID,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCartItem = `-- name: RemoveCartItem :exec
DELETE FROM cart_items WHERE cart_id = $1 AND book_id = $2
`

type RemoveCartItemParams struct {
	CartID uuid.NullUUID
	BookID uuid.NullUUID
}

func (q *Queries) RemoveCartItem(ctx context.Context, arg RemoveCartItemParams) error {
	_, err := q.db.ExecContext(ctx, removeCartItem, arg.CartID, arg.BookID)
	return err
}

const updateCartItemQuantity = `-- name: UpdateCartItemQuantity :exec
UPDATE cart_items
SET
    quantity = $1,
    updated_at = $2
WHERE
    cart_id = $3
    AND book_id = $4
`

type UpdateCartItemQuantityParams struct {
	Quantity  int32
	UpdatedAt sql.NullTime
	CartID    uuid.NullUUID
	BookID    uuid.NullUUID
}

func (q *Queries) UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) error {
	_, err := q.db.ExecContext(ctx, updateCartItemQuantity,
		arg.Quantity,
		arg.UpdatedAt,
		arg.CartID,
		arg.BookID,
	)
	return err
}
