// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"database/sql"
	"github.com/NguyenAnhQuan-Dev/NKbook-API/internal/handlers"
	"github.com/NguyenAnhQuan-Dev/NKbook-API/internal/repositories"
	"github.com/NguyenAnhQuan-Dev/NKbook-API/internal/services"
	"github.com/redis/go-redis/v9"
)

// Injectors from user.wire.go:

func InitAuthHandler(db *sql.DB, client *redis.Client) (*handlers.AuthHandler, error) {
	iUserRepository := repositories.NewUserRepository(db)
	iAuthService := services.NewAuthService(iUserRepository)
	iCache := services.NewCacheService(client)
	authHandler := handlers.NewAuthHandler(iAuthService, iCache)
	return authHandler, nil
}
