// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO
    users (
        id,
        email,
        password,
        username,
        role,
        status
    )
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateUserParams struct {
	ID       uuid.UUID
	Email    string
	Password string
	Username string
	Role     sql.NullString
	Status   sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Password,
		arg.Username,
		arg.Role,
		arg.Status,
	)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password, username, role, status
FROM users
WHERE
    email = $1
`

type GetUserByEmailRow struct {
	ID       uuid.UUID
	Email    string
	Password string
	Username string
	Role     sql.NullString
	Status   sql.NullString
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.Username,
		&i.Role,
		&i.Status,
	)
	return i, err
}

const userExists = `-- name: UserExists :one
SELECT EXISTS (
        SELECT 1
        FROM users
        WHERE
            username = $1
            OR email = $2
    )
`

type UserExistsParams struct {
	Username string
	Email    string
}

func (q *Queries) UserExists(ctx context.Context, arg UserExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, userExists, arg.Username, arg.Email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
